[project]
name = "lesoon-uc"
version = "0.1.0"
description = "User Center service"
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "pydantic-settings",
    "uvicorn",
    "lesoon-auth",
    "lesoon-core",
    "lesoon-uc-api",
]

[tool.uv.sources]
lesoon-auth = { workspace = true }
lesoon-core = { workspace = true }
lesoon-uc-api = { workspace = true }

[build-system]
requires = ["uv_build>=0.10.9,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "lesoon.uc"
