[project]
name = "novon-uc"
version = "0.1.0"
description = "User Center service"
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "pydantic-settings",
    "uvicorn",
    "novon-auth",
    "novon-core",
    "novon-uc-api",
]

[tool.uv.sources]
novon-auth = { workspace = true }
novon-core = { workspace = true }
novon-uc-api = { workspace = true }

[build-system]
requires = ["uv_build>=0.10.9,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "novon.uc"
