[project]
name = "zrun-uc"
version = "0.1.0"
description = "User Center service"
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "pydantic-settings",
    "uvicorn",
    "zrun-auth",
    "zrun-core",
    "zrun-uc-api",
]

[tool.uv.sources]
zrun-auth = { workspace = true }
zrun-core = { workspace = true }
zrun-uc-api = { workspace = true }

[build-system]
requires = ["uv_build>=0.10.9,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "zrun.uc"
